# Generated by Django 3.2.3 on 2021-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBranch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank_id', models.BigIntegerField()),
                ('branch', models.CharField(max_length=74)),
                ('address', models.CharField(max_length=195)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=26)),
                ('bank_name', models.CharField(max_length=49)),
            ],
            options={
                'db_table': 'api_branch',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
