# Generated by Django 3.2.3 on 2021-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210516_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('ifsc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('bank_id', models.BigIntegerField()),
                ('branch', models.CharField(max_length=74)),
                ('address', models.CharField(max_length=195)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=26)),
                ('bank_name', models.CharField(max_length=49)),
            ],
            options={
                'db_table': 'bank_branches',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ApiBranch',
        ),
    ]
