# Generated by Django 3.2.3 on 2021-05-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210516_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=49)),
            ],
            options={
                'db_table': 'banks',
                'managed': False,
            },
        ),
    ]
